spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: WEMpIegzZQGPi+VtO6JWT+ufB7yLE06CSed4dkv5DhkZEtjAowv36EN+uoVePp7v
    username: WH0aR1G9UMJFUZfLGfDd9g==
    password: vtYbI6+CxfALyXFHdlCBcw==
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      use_sql_comments: true
      format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
mail:
  host: PDLHLGCVjy1AOCuq/vU2sg==
  username: itilLqVuKih/3fhESJHrUlZiQ02Vzr9uWq4iD4Hb5IE=
  password: 2yC3mLymqaIOZypeZNFPIohmZbYwya2+dyu3JJRSRCc=

logging:
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %logger{35} - %msg%n"
  level:
    root: info
  file.name: /logs/sign.log
  logback:
    rollingPolicy:
      file-name-pattern: "/logs/sign-%d{yyyy-MM-dd}-%i.log"
      max-file-size: 100MB
      max-history: 30