
name: Sign Application Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "RELEASE"
        required: true
        default: "release v0.1"
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: execute gradle
      run: chmod +x ./join/gradlew
      
    - name: build java
      run: cd ./join  && ./gradlew clean build
            
    - name: Jar deploy
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "join/build/libs/join-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/sign"
          
    - name: deploy dockerfile
      uses: appleboy/scp-action@master  
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "join/dockerfile"
          target: "/home/ubuntu/sign"
          
    - name: deploy sign-app
      uses: appleboy/ssh-action@v0.1.6
      with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.ID }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo sh sign/join/deploy.sh
